### ISSUE TITLE
gulp does not re-compile js  

### ISSUE THREAD

**Issue by w0rldart** [jadjoubran/laravel5-angular-material-starter#11]
Is it only me experiencing the issue where executing `gulp` won't re-compile any `.js` files from inside `angular/` directory?

the `.angular()` directive should output the updated app.js, but it doesn't. I've also tried `.angular('angular/', 'public/js/', 'app.js')` with same result.

Any ideas?

**Comment by jadjoubran** [comment]
I guess the issue is that you have a jshint issue.

![git bash](https://cloud.githubusercontent.com/assets/2265232/7903388/a4c141cc-07e3-11e5-9fd2-c3108310d86b.png)

when you see a similar warning then it won't recompile your JavaScript.

If you don't want it to lint jshint, you can just delete the .jshintrc file.

Let me know if it works for you

**Comment by hafeez1042** [comment]
Hi jadjoubran
Have the same issue, but i cant find .jshintrc file.
Can you give me the location of  .jshintrc file.
Thankyou.

**Comment by jadjoubran** [comment]
Thank you for your report!
Here's the .jshintrc file in the repository https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/.jshintrc
So it's at the root level of your project. On windows, it might be hidden by default because the file starts with a dot. If you're not interested in jshint, you can simply remove the file.

Let me know if either of the methods works for you
Thanks!

**Comment by hafeez1042** [comment]
![image](https://cloud.githubusercontent.com/assets/7904196/8323244/37f75f48-1a5f-11e5-8c03-377b66b0ef56.png)

after removing .jshintrc file getting the above warning.

**Comment by hafeez1042** [comment]
Thanks bro. Issue solved.   :)

**Comment by jadjoubran** [comment]
Okay great! I'll update the documentation asap

**Comment by jadjoubran** [comment]
With [2.7.0](https://github.com/jadjoubran/laravel5-angular-material-starter/releases/tag/2.7.0) you can now enable jshint and it'll simply report the warnings without failing. I also made the `gulp` tasks 4 times faster!

I'd love to get your feedback.
Thanks!

**Comment by w0rldart** [comment]
(y)

**Comment by w0rldart** [comment]
:thumbsup:
