### ISSUE TITLE
Angular 2 Upgrade?

### ISSUE THREAD

**Issue by ChadTaljaardt** [jadjoubran/laravel5-angular-material-starter#126]
Hello, 

Ive been looking at this  project recently trying to keep updated with whats going on. I must say, it looks really really nice now. 

I just want to ask if there is plans to upgrade to Angular 2.0?

Its still in beta so i don't see it happening any time soon but is it planned?

**Comment by jadjoubran** [comment]
Hi @ChadTaljaardt 

Thanks :smile: 

Angular 2.0 is definitely on the list. But I'm not sure if it would be suitable to do it before at least having a release candidate of Angular 2..

Updating vendor library usually depends on the availability of plugins that this library is using.. For example, I had to wait for `jwt-auth` and `dingo/api` to be compatible with Laravel 5.2 so I can start the upgrade ( #121 )..

But I'm guessing we won't be facing this issue here (mainly with ui-router, angular material, etc..) because of the `ng-upgrade` which allows including angular 1 components within an angular 2 app.

I'm going to keep this opening, if anyone would like to work on this, let's collaborate

**Comment by ptondereau** [comment]
I think it'll be better to smoothly update the code based on the 1.x's incrementations because Angular's developers tries to force users to migrate every incr to Angular 2 syntax. But non open source porject, companies will still use Angular1 as reference as long as ther will be LTS on It (about ~5y)

**Comment by jadjoubran** [comment]
@rooferz I think you misunderstood me
1.x will be definitely upgraded (when 1.5 is released, we'll definitely upgrade to it) since this is a starter project that encourages best practices (angular's `.component`)

However including angular 2 when in beta might not be very wise, so we'll probably wait for a release candidate or official release before upgrading to angular 2

Let me know what you think :smile:

**Comment by ptondereau** [comment]
@jadjoubran this is exactly what I want to tell you x) 
Sorry, hangover time

**Comment by jadjoubran** [comment]
haha awesome!

**Comment by jadjoubran** [comment]
Just released 3.2
I will close this issue as the next release will definitely be about Angular 2
so the planning will be on the [trello board](https://trello.com/b/tZ997reo/laravel-angular-material-starter)
