### ISSUE TITLE
URI Issue When Not Using PHP Artisan Serve

### ISSUE THREAD

**Issue by bravocado** [jadjoubran/laravel5-angular-material-starter#131]
I have my own virtual server. But when i'm trying to open `virtual.dev/project/public/` I got an error 404 for some assets when i'm not using `php artisan serve`.

Trying to change these to fix the issue:
- angular/app/landing -- landing.html -- `/img/` to `img/`
- angular/app/landing -- landing.less -- `/img/` to `../img/`
- angular/app/footer -- footer.html -- `/img/` to `img/`

Quick fix not affecting when using `php artisan serve`.

Do you mind to change the URI so it's compatible to our own virtual server?

**Comment by jadjoubran** [comment]
HI @bravocado
Thanks for opening an issue here

So if I understood you correctly, it all comes down to `absolute paths` (`/img/`) vs `relative paths` (`img/`).. 
I think absolute paths are recommended because they always work in all scenarios.
Having said that, it's always better to setup a virtual host per project..
so you would do `project.dev` which has a document root of `../project/public`

It wouldn't make sense to change the routes and break them for everybody

Let me know if this works for you :smile:

**Comment by bravocado** [comment]
yeah i think this issue too personal. Thanks for the idea. :)
