### ISSUE TITLE
A through cleanup of dependencies required, I guess

### ISSUE THREAD

**Issue by UnrulyNatives** [jadjoubran/laravel5-angular-material-starter#133]
Today I tried to install the project, using the procedure proposed here: 
https://laravel-angular.readme.io/docs/install.

Unfortunately I have run on multiple dependency issues, such as 
messages about depreciated packages when installing NPM: 
    "gulp-minify-css": "^0.3.11",
    "gulp-minify-html": "^1.0.3",

When installing bower (`bower install`) I got issues such as this:
`UNMET PEER DEPENDENCY vueify-inser-css@^1.0.0` 
and
npm WARN EPEERINVALID laravel-elixir-livereload@1.1.4 requires a peer of laravel-elixir@^4.0 but none was installed.
The first quoted issue produced 
`npm WARN EPEERINVALID vueify@5.0.4requires a peer of vueify-inser-css@^1.0.0 but none was installed`

Maybe someone should take a closer look at the issues. 
BTW, the installation went successful.

Thx

**Comment by jadjoubran** [comment]
Hi @UnrulyNatives 
Thanks for reporting this

Yes the installation is expected to be successful.. and everything should work
Since the deprecation of most packages just implies that there are new ones with newer options
I'm trying to update the following
- [x] gulp-minify-css
- [x] gulp-minify-html
- [x] updated to laravel-elixir 4

There might be some warnings related to laravel-elixir 4 but I'm still waiting for a third party library to fix their dependencies so I can update

**Comment by jadjoubran** [comment]
@UnrulyNatives Would you be able to test and report if it's working? (I have a terrible connection, and npm install took 2+hours)

You can install the latest unstable using the following command

`composer create-project jadjoubran/laravel5-angular-material-starter=dev-master`

**Comment by jadjoubran** [comment]
I was able to test now, and it seems working well
So I'm closing this for now
But I'd love to get a confirmation for you if it solves all issues or if you have other comments
