### ISSUE TITLE
Page not found message

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#136]
Hi,

I tried to follow your tutorial to create public frontend route and did this:
1. Ran php artisan ng:directive test_form
2. Edited angular/directives/test_form/test_form.html and test_form.directive.js
3. Ran php artisan ng:feature test_form
4. Added test_form directive to angular/app/test_form/test_form.html
5. Added test_form state to angular/routes.js
6. Run gulp

When browsing to test_form, browser gives not found message.. What went wrong?

Thanks!

**Comment by jadjoubran** [comment]
Hi @regisaih 
Thanks for opening an issue.

I guess you're trying to navigate to:
`localhost:8000/test_form`
instead of
`localhost:8000/#test_form`

If that's the issue, it's because we don't enable HTML5 URLs by default.. you probably don't need to worry about this if you're using the `ui-sref` directive from UI-router
Alternatively you can enable HTML5 mode as discussed here #118 

Let me know if this solves your issue

**Comment by ghost** [comment]
That solved my issue...well not really an issue. I consider to move html5 mode. Thanks a lot for support!
