### ISSUE TITLE
Angular-translate

### ISSUE THREAD

**Issue by shiruken1** [jadjoubran/laravel5-angular-material-starter#148]
Would there be interest in integrating the starter with Angular-translate? I'll be doing so on my app, but can make a PR out of it if y'all want :smile:

**Comment by ChadTaljaardt** [comment]
I think this is a good idea :+1:

**Comment by jadjoubran** [comment]
Hi @shiruken1 
Thanks again for your interest :smile: 

I think this is a great time for me to start working on the recipes.. all of the suggestions that I've been getting today make a lot of sense if they were implemented as recipes..
Since, as I mentioned in #143, the main differentiation for this package, is that it doesn't ship with way too many unused vendors..
For example I wouldn't use angular-translate if I'm not doing i18n or l10n..

But it seems that @ChadTaljaardt would need this..
Hence the need for a plugin/recipe system :smile: 

I'll need to think about a way to implement the recipes/plugins architectures so I'll ping you as soon as I have something in mind
Feel free to share your suggestions

Thanks!

**Comment by shiruken1** [comment]
Makes sense. Let me know what I can do to make recipes happen. I think they're the best of both worlds! (like scaffolding generators, but more meaningful, and like an all-in-one boiler, but less bloated)

I haven't taken a look at ChuckHeintzelman's repo yet, but I believe with a strong enough community, recipes could make Laravel into a developer's Wordpress! :smile:

**Comment by jadjoubran** [comment]
Hi @shiruken1 
I created a new issue for that!

**Comment by shiruken1** [comment]
Awesome, thanks! I'll be looking into it soon.
