### ISSUE TITLE
Lumen?

### ISSUE THREAD

**Issue by edmundluong** [jadjoubran/laravel5-angular-material-starter#15]
Hey Jad,

I was wondering if there were any plans to support Laravel's new microframework, [Lumen](http://lumen.laravel.com/). Since Laravel is being used as a REST API in this project, Lumen could serve the same role as Laravel but with significant performance improvements.

I would love to hear your thoughts. Thanks and best regards.

**Comment by jadjoubran** [comment]
Hi @edmundluong

thanks a lot for this great suggestion!

I've thought about Lumen but the problem here is the following:

How can I provide support for both Laravel and Lumen without having to duplicate all the changes across 2 different branches? And without turning this package into a generator.

Let's discuss the possible solutions, and I'd be happy to implement it!

I chose Laravel because most developers are used to it and sometimes you might need a package that is not available in Lumen and you're not really interested in premature optimization.

Looking forward to hearing from you!

**Comment by GrahamCampbell** [comment]
I don't really think diving into Lumen is a good idea. Just going to cause a headache and add more things to maintain.

**Comment by jadjoubran** [comment]
I agree with Graham. So I'm closing this for now.
But feel free to re-open if you have more info/suggestions for this

**Comment by 3kynox** [comment]
I was looking running this project with Lumen also. Maybe more things to maintain but you have the choice to chose which parts you need and run on a faster solution.

The way to do things here could be a separated repo.

Thanks anyway.

**Comment by jadjoubran** [comment]
@3kynox I will make http://github.com/jadjoubran/laravel-angular as a package so that it can work with either Laravel or Lumen 💡
