### ISSUE TITLE
Upgrading laravel5-angular-material-starter pack

### ISSUE THREAD

**Issue by edbentinck** [jadjoubran/laravel5-angular-material-starter#150]
What would you suggest as the easiest way to upgrade an existing repo based on `laravel5-angular-material-starter v2.10.*` and adding the improvements made in `v3.0`?

There are many improvements that I'd like to integrate into my project but I'd rather not have to do it all manually :)

**Comment by jadjoubran** [comment]
Hi @edbentinck 
Would you be able to describe more about the existing functionality in your 2.10 app?
- Are you using Restangular to call your API?
- Are you using the response macro provided? (`response()->success()` and `response()->error()`)

Because I think these are the 2 main breaking changes..
So depending on your answers, it might be much easier for you to start with a fresh installation and copying your previous files (Just like you'd do when upgrading from Laravel 4.3 to 5.0)

**Comment by edbentinck** [comment]
Hmm, I think you could be right. I think it probably would be easier to go with a fresh install.

I hadn't made too many changes to the fresh install of 2.10, but I notice that since then there are a number of alterations to the standard Laravel (and Angular) install dotted around the app, so it might be too much hassle to manually upgrade. Unless of course you wanted to create an Upgrade Guide, like [the one offered by Laravel](https://laravel.com/docs/master/upgrade#upgrade-5.2.0), but probably not worth it ;)

Thanks for the info and keep up the great work!

**Comment by jadjoubran** [comment]
@edbentinck it's already there :smile: 
https://laravel-angular.readme.io/docs/upgrade-guide
But it recommends you do it with a fresh installation.. it's going to be even faster for you, since you're upgrading from 2.10

**Comment by edbentinck** [comment]
Ohh! :sweat_smile: My bad, I didn't spot that!
That's awesome!

**Comment by jadjoubran** [comment]
No worries :smile:
Feel free to report any issues that you face along the way - or anything that you deem unclear
