### ISSUE TITLE
Ide helper integration

### ISSUE THREAD

**Issue by franklupo** [jadjoubran/laravel5-angular-material-starter#159]
Hi,
is possible integrate **ide helper** 'barryvdh/laravel-ide-helper'  in composer,json?

> "barryvdh/laravel-ide-helper": "^2.1"

in pre update command

>   "pre-update-cmd": [
>             "php artisan clear-compiled",
>             "php artisan ide-helper:generate",
>             "php artisan optimize"
>         ],

Thanks. 
Best work

**Comment by franklupo** [comment]
Add .gitignore 

> _ide_helper.php

**Comment by jadjoubran** [comment]
Hi @franklupo 
Thank you so much for requesting this feature
It is indeed very easy to setup, however this would look weird if someone's not using an IDE
So also for example `_ide_helper.php` could go into your global .gitignore so that you don't have to set it up per project
Let me know what you think

**Comment by franklupo** [comment]
This file  **_ide_helper.php** is generated.

> php artisan ide-helper:generate

If you add new package this file is regenerate.

**Comment by jadjoubran** [comment]
Hi @franklupo 
Thanks again for your feedback
Yes I do understand, but the problem is we always try to keep this useful for everyone.. I understand that this is useful for all IDE users but it won't make any sense for non-IDE users
Feel free to open a new issue if you have other suggestions
Thanks!
