### ISSUE TITLE
Login example request

### ISSUE THREAD

**Issue by afarazit** [jadjoubran/laravel5-angular-material-starter#168]
Can you provide a full example (backend/frontend) for login in a user?

**Comment by jadjoubran** [comment]
Hi @afarazit 
This will be provided in #151 

Regarding the backend, the LoginController is a great example
Regarding the front-end.. I really think it's a normal feature.. a bit similar to the one covered in the screencasts..

I know that a link between both of them is missing.. but this will be definitely provided in #151

**Comment by odyright** [comment]
hello @jadjoubran 
(concerning your screencast) instead of having text in the the variable `vm` i tried to insert form input with submit button like this:
inscription-form.directive.js

``` javascript
(function(){
    "use strict";

    angular
        .module('app.controllers')
        .controller('InscriptionFormController', InscriptionFormController);

            function InscriptionFormController(){
                var vm = this;

                vm.titre = "Formulaire d'inscription";
                vm.form =   [
                    {
                        key: 'Matricule',
                        type: 'input',
                        templateOptions: {
                            label: 'Input'
                        }
                    },
                    {
                        elementAttributes: {
                            layout: 'row',
                            'layout-sm': 'column'
                        },
                        fieldGroup: [
                            {
                                "key": "nom",
                                "type": "input",
                                "templateOptions": {
                                    "label": "Nom",
                                    "pattern": "[a-zA-Z]+"
                                },
                                "validation": {
                                  "messages": {}
                                }
                            },
                            {
                                key: 'Prénom',
                                className: 'flex',
                                type: 'input',
                                templateOptions: {
                                    label: 'Prénom'
                                },
                                "validation": {
                                  "messages": {}
                                }
                            }
                        ]
                    },
                    {
                        key: 'knowsMuffinMan',
                        type: 'checkbox',
                        templateOptions: {
                            label: "J'ai lu et j'accepte les conditions."
                        }
                    }
                ];
            }

})();  
```

then in : inscription-form.html

```
<p>
{{vm.titre}}
</p>
<p>
{{vm.form}}
</p> 
```

and : inscription.html

```
<md-content class="Inscription" ng-controller="InscriptionController as vm">

    <h2>FORMULAIRE D'INSCRIPTION</h2>

    <inscription-form></inscription-form>
    <br/>

 </md-content> 
```

it didn't show any form but i got this: 

![screen shot 2016-02-16 at 15 15 39](https://cloud.githubusercontent.com/assets/4316506/13080492/cb3e53b2-d4c0-11e5-85c9-51816f1d1dcb.png)

could you help me? @Bodom78 may be you could give me some advise! :+1:

**Comment by jadjoubran** [comment]
hm.. you are printing `vm.form`.. which is an array
this is why it's showing like this..
I'm guessing you're using (or you want to use) angular-formly to generate this form?

**Comment by odyright** [comment]
hi, 
Mmm..no Angular-formly for material desgn is still in dev , I would have loved to use it but I wanted to do it by myself. As I have errors I would like to know how to display the form correctly.

**Comment by jadjoubran** [comment]
Where do you see the errors?
Could you show me your console?

**Comment by odyright** [comment]
her you are
![capture d ecran 2016-02-17 a 23 02 15](https://cloud.githubusercontent.com/assets/4316506/13128010/b94d79f2-d5ca-11e5-837e-f1832ae0a923.png)

**Comment by jadjoubran** [comment]
Hi @odyright 
This is a plugin called [eslint](http://eslint.org/). You can consider these as warnings that help you **improve** your code quality.
You don't seem to have an error in your application. However to check that, you need to show me the output of your Chrome console.

But I'm guessing that you don't have any issue, since you're outputting json and you're getting json

**Comment by odyright** [comment]
Haahh.. i understand now (I really looks like a beginner)... and I think that the problem was not understood, I wanted to have a guide on how to make a form using the diretives or the services etc for angularjs (if it is possible). But do you advise me to use angular formly instead of doing it myself?

**Comment by edbentinck** [comment]
Out of interest, @jadjoubran, how do you plan on implementing this?

1) As a public app, whereby most routes are open and only some routes require authentication.
2) As a private app, whereby the user must be authenticated to access all routes – except for a `login` state, of course.

I ask because depending on the type of app it could impact the structure. I'm currently developing a private app (i.e. use case 2) and in order to display a clean Login screen I've applied `ng-if` conditions on the Sidebar and Header elements in `index.blade.php`. It doesn't feel like the best approach, but having toyed around with the idea of restructuring the views it was the cleanest solution I could come up with.

What are your thoughts?

**Comment by jadjoubran** [comment]
Hi @odyright I never tried formly before but I personally construct the forms manually.. I think that would work for you

Hi @edbentinck 
The idea is to leverage this to ui-router
Here's an example:

```
//base layout for protected routes
.state('app', {
        abstract: true,
        views: {
            header: {
                templateUrl: getView('header')
            },
            footer: {
                templateUrl: getView('footer')
            },
            main: {}
        }
    })
    //base layout for public routes
    .state('public', {
        abstract: true,
        views: {
            main: {}
        }
    })

    //public
    .state('public.login', {
        url: '/',
        data: {},
        views: {
            'sidebar@': {
                template: ''
            },
            'main@': {
                templateUrl: getView('landing')
            }
        }
    })
    //protected
    .state('app.dashboard', {
        url: '/dashboard',
        data: {
            user: 'admin'
        },
        views: {
            'main@': {
                templateUrl: getView('dashboard')
            }
        }
    });
```

**Comment by jadjoubran** [comment]
So using this example we defined 2 layouts, 1 for protected routes and another one for public routes.
You could also manually override some of the templates inside one of the routes.
Note that the layouts have abstract: true and cannot be directly called.

You can also pass in some `data` arguments that can be processed by ui-router to run your own front-end logic for authentication (this is just for the user experience)

References:
- [abstract states](https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views#abstract-states)
- [multiple named views](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views)
- [State change events to read data arguments](https://github.com/angular-ui/ui-router/wiki#state-change-events)

Let me know what you think, as this will probably be the way to go after 3.1 is released

**Comment by odyright** [comment]
hi @jadjoubran i tried to do it manually (following your doc & screencast) I've searched for a long time on google how to make a form manually with best practices but without convincing result...

**Comment by jadjoubran** [comment]
Hi @odyright I don't think there are best practices for a form..
You can just use a form from Angular Material's documentation

https://material.angularjs.org/latest/demo/input

You can use their code as a base to what you're planning to do

**Comment by osamasd** [comment]
*// register.html*

<form>
<input type="email" ng-model="data.email">
<input type="password" ng-model="data.password">

<button ng-click="vm.register(data)">Register</button>
</form>

*// registerController.js*

vm.register = function(data) {

      var email = data.email;

        var password = data.password;
  }

*note*: i'm  just replaying your last replay.

**Comment by odyright** [comment]
hi @jadjoubran, @osamasd has in part answered my problem... when we use `controlleras vm` like john ppa style....
hi @osamasd, i think you were replaying to me. I'd really like you give me more detail.

**Comment by osamasd** [comment]
@odyright what do you want to do exactly ?

**Comment by odyright** [comment]
@osamasd i want to do / how to make a complex registration form such like an admission application form for students.

**Comment by jadjoubran** [comment]
Closing in favor of #151

**Comment by edbentinck** [comment]
Thanks for your response to my question, @jadjoubran... I'm only just finding the time to reply.

My implementation was very similar to that which you described. However, I'm still left wondering about the changes to the `index.blade.php` DOM. With the example that you give, surely you must still have to apply `ng-if` conditions to the Sidebar and Header elements on `index.blade.php`? Either that or extract the "base" structure of each of those elements into their respective template files (i.e. sidebar.html), so that they're no longer hardcoded in the root DOM structure.

Or am I missing something?

**Comment by odyright** [comment]
@osamasd haven't you suggestion?

**Comment by jadjoubran** [comment]
@edbentinck no I never touch the `index.blade.php`
I just do it once according to my app structure and that's it..
You could create 2 different app templates in your route.. for example one that expects a `header`, `sidebar` and `main`
and another one that only expects `main`.. leaving the definition empty for sidebar would not show the sidebar (without having to apply an `ng-if`)
and then you could extend these 2 templates in your routes just like we did with `app.etc`

**Comment by edbentinck** [comment]
@jadjoubran Ahhh! I've just seen that you changed the structure of `index.blade.php` since the version that I'm using. No wonder I was getting confused! :stuck_out_tongue_closed_eyes: Makes sense with the new structure now. Awesome!

**Comment by jadjoubran** [comment]
:smile:
