### ISSUE TITLE
Component not showing

### ISSUE THREAD

**Issue by nikeshbhagat** [jadjoubran/laravel5-angular-material-starter#177]
Hello,

First - great work. Really helpful!

I'm using the latest version and I've made sure I'm using Angular 1.5 since this was this main problem referenced in issue #164 related to components.

My issue may be nothing at all, but I thought I'd bring it up here as it may help someone else.

I _was_ having an issue with a component not showing up in my page template when I was doing the following:

**index.components.js**
`angular.module('app.components').component('registerForm', registerFormComponent);`

**register-form.component.js**

```
export function registerFormComponent() {
    'ngInject';

    var component = {
        templateUrl: './views/app/components/register-form/register-form.component.html',
        controller: RegisterFormController,
        controllerAs: 'ctrl',
        bindToController: true
    };

    return component;
}

class RegisterFormController{
    constructor(){
        'ngInject';
        var vm = this;
        vm.name = 'John Smith';
    }
}
```

When I change **index.components.js** to include **()** on 'registerFormComponent':

`angular.module('app.components').component('registerForm', registerFormComponent());`

Everything works.

My question is definitely a bit amateurish, but is this the correct way to pass the component config object?

Thanks in advance.

**Comment by jadsalhani** [comment]
If we take a look at the angular component [documentation](https://docs.angularjs.org/guide/component), we see that the `.component` module doesn't take a function as a second argument like the `.directive` did.

So @nikeshbhagat, That's why adding `()` to the `registerFormComponent` made it work, you were calling the function and thus returning the component object.

I think now the export should be for a variable rather than a function, unless someone prefers to keep the same syntax and just call the functions with the `()` in the module declaration (not sure how much each is recommended, I guess it's just preference)

The export could be something like:

```
export const component = {
  // Your options here
}
```

and then just adding the component import without the `()` would work.

**Comment by jadjoubran** [comment]
yeah so this is probably a bug, thanks @jadsalhani and @nikeshbhagat 
Good thing you were able to spot that before the release :smile:

**Comment by nikeshbhagat** [comment]
Thanks @jadjoubran and @jadsalhani .

@jadsalhani I did notice in the documentation that the `.component` method does not take a function , which is what spawned my curiosity. Thank you for the explanation.  I agree that the export should be for a variable rather than a function, but I'm also unsure of the 'best practice' in this particular scenario.

@jadjoubran No problem. And thanks again for putting together such a great starter as well as for the recent enhancements to get it Angular 2.0 ready.

**Comment by jadjoubran** [comment]
I just published the [v3.1 documentation](https://laravel-angular.readme.io/v3.1/docs) - currently in draft mode.

I would love to get some feedback, proof reading, comments, etc.. :smile: 
Thanks!

**Comment by nikeshbhagat** [comment]
@jadjoubran Awesome! Thanks for letting me know and sorry for the delay in getting back to you.

I'll take some notes as I continue to use `laravel5-angular-material-starter` and give you some feedback when I've compiled a decent list.  How would you like to receive the feedback? Here?

Also, if there's anything specific you'd like re: feedback, proof reading, comments - just let me know. Happy to help.

One thing right off the bat that I've noted as being potentially helpful would be the ability to use the angular generators in such a way that allows you to create components, pages, etc. in nested folders to enhance organisation. For example, `artisan ng:component map/map_controls`, which would create the three component files in `./components/map/map_controls`. Does this make sense? You could then have `./components/map/map_nav`, etc. Do you think it would benefit the folder by feature architecture?

**Comment by jadjoubran** [comment]
Hi @nikeshbhagat 

It would be great if you can give me your feedback (also proof reading and comments) for the updated documentation. Feel free to create a new issue so maybe other people can also give their feedback.
But keep in mind that the installation section would install the previous version for now since I haven't tagged the v3.1 release. However you can use this command instead: `composer create-project jadjoubran/laravel5-angular-material-starter:dev-master`

And yes I think it would be a great idea for some project
Would you mind opening an issue (or PR) on this repo or the [generators](https://github.com/jadjoubran/laravel-ng-artisan-generators) one?

Thank you for your contribution :smile:
