### ISSUE TITLE
Sidebar issue on IE11

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#18]
Originally posted by @bodom78 - issue #16

![IE bug](https://cloud.githubusercontent.com/assets/139152/9112764/0cd94ce8-3c94-11e5-87b4-bac980f2470a.JPG)

I have some workarounds in the `sidebar.html` code for the `ui-sref` to work.. So this might be causing an issue on IE11..
But then I noticed that this is an upstream issue on angular/material repo:

https://github.com/angular/material/issues/2131

I'm pushing a temporary fix as mentioned in this [comment](https://github.com/angular/material/issues/2131#issuecomment-113938582) until the upstream issue is resolved.

**Comment by jadjoubran** [comment]
@bodom78 Let me know if this works for you on IE11

**Comment by Bodom78** [comment]
Links work fine in IE, the styling issue remains.

Looks like the vertical text alignment on a list item in IE can be fixed by adding a height to md-list-item as discussed at https://github.com/angular/material/issues/3764

Testing in the DOM Explorer confirms this works but it is really a hack just for IE to work. Only problem would be if you had 3 lines of text on a menu item which is unlikely.

![ie-list-fix](https://cloud.githubusercontent.com/assets/139152/9187799/f5eca782-4017-11e5-9246-e43e15be96d7.JPG)

**Comment by jadjoubran** [comment]
Oh okay.. that's great
I tried to see how https://material.angularjs.org/ were able to make it work in the their side-menu.. but I guess there's a line-height or padding that's making it work..
So I'm going to add a fixed height for it..

Thanks a lot for your help :D

**Comment by jadjoubran** [comment]
@Bodom78 let me know if it fixes it, so I can close the issue
Thanks!

**Comment by Bodom78** [comment]
Looks good and working fine in IE11 now.

**Comment by jadjoubran** [comment]
Great, thanks!
