### ISSUE TITLE
How to compile in 'vendor.css' css files from bower_components 

### ISSUE THREAD

**Issue by intrepido** [jadjoubran/laravel5-angular-material-starter#186]
I added for testing de `angular-bootstrap` library and when I execute 

> gulp && gulp watch 

command the .js files are complied in `vendor.js`, but the .css files isn't compiled in `vendor.css`. Is there something wrong in `bower.task.js`?

**Comment by jadjoubran** [comment]
Hi @intrepido 
The problem seems to be [angular-bootstrap's bower.json](https://github.com/angular-ui/bootstrap-bower/blob/master/bower.json) file:
They don't have the css mentioned in their `main` attribute.

These issues on their repo discuss some possible solutions:

https://github.com/angular-ui/bootstrap-bower/issues/62
https://github.com/angular-ui/bootstrap-bower/pull/63
https://github.com/angular-ui/bootstrap-bower/issues/18

**Comment by intrepido** [comment]
@jadjoubran Thanks I already resolved the problem, I installed the css with

> bower install bootstrap-css-only --save

and now all work fine. I had forgotten to use `--save` param

**Comment by jadjoubran** [comment]
okay great!
