### ISSUE TITLE
404 for endpoint: http://localhost:8000/posts

### ISSUE THREAD

**Issue by yunus89** [jadjoubran/laravel5-angular-material-starter#188]
Hi @jadjoubran ,

When i post `/posts` using rectangular
rectangular code

```
    this.Restangular.all('posts').post(data).then(function(response){     
          this.ToastService.show('Post added successfully');
    });
```

i see a 404 in Network tab(Inspect element). Even though i have correctly setup route in laravel `app/Http/route.php` .

Code in laravel's routes.php:

```
     $api->group([], function ($api) {
            $api->post('users/login', 'LoginController@login');
            $api->post('posts', 'CreatePostController@create');
     });
```

Bare my ignorance; why a 404, when the route is right there?

**Comment by jadjoubran** [comment]
Hi @yunus89 
I just discovered this issue 10 minutes ago in #181 
The documentation used to mention `Restangular` but in fact you should use `API` which is pre-configured to work properly with the API.

The route you're looking for is available at `/api/posts`. But as soon as you switch to using API instead of restangular it should work.

Also keep in mind that you might face one of these issues until they have been resolved #187

**Comment by yunus89** [comment]
Thanks, changing all occurances of  `Rectangular` to `API` solved my problem.

**Comment by jadjoubran** [comment]
Great!
