### ISSUE TITLE
405 - Method not allowed

### ISSUE THREAD

**Issue by vampire1306** [jadjoubran/laravel5-angular-material-starter#198]
I login successfully and receive the JWT.
Then I try to submit (post method) to a route that require login.
It keeps saying method not allowed, though I see the token in the request's header:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1NjY1NDRiOWI5NjkxOGNjMjEwMDAwMjkiLCJpc3MiOiJodHRwOlwvXC9sdHV0b3JpYWwudm5cL2FwaVwvbG9naW4iLCJpYXQiOjE0NTc2Njc0NTYsImV4cCI6MTQ1NzY3MTA1NiwibmJmIjoxNDU3NjY3NDU2LCJqdGkiOiJhYjE2ODE2ZGY1NWIxYjJjMWFhOTA5MWQ0NDhmZWYyYiJ9.redC_YDMtdQsfVuOdwYTcT3R7046IvKt6fz2H2OukgU

I try to get the token by PostMan app, and I get the same token.
The version with laravel 5.1 works well with JWT, but this version with 5.2 is not.

**Comment by jadjoubran** [comment]
Hi @vampire1306 
Thanks for posting an issue here

I just tried the following on a fresh installation and it does work.
However the process is not straightforward, until we're done wiht #151 or #41 

As long as you save the token in localStorage as jwt (`$localStorage.jwt`) or you send it manually, you can make it work

I suspect you are doing a `POST` instead of a `GET` because the error says Method not allowed it means you're using a different HTTP verb

**Comment by vampire1306** [comment]
Sorry, my bad!
It's exactly as you suspect.
Thanks for your good work ^^

**Comment by jadjoubran** [comment]
Sounds great!
