### ISSUE TITLE
Gulp does  not automatically load bower installed css - updated: Font awesome issue

### ISSUE THREAD

**Issue by kujtimiihoxha** [jadjoubran/laravel5-angular-material-starter#205]
I installed font-awesome through bower but gulp is not loading font-awesome css.

**Comment by jadjoubran** [comment]
Hi @kujtimiihoxha 
You need the `--save` flag when installing it

[docs](https://laravel-angular.readme.io/docs/elixir)

Let me know if that fixes your issue

**Comment by kujtimiihoxha** [comment]
@jadjoubran I actually did  `--save`  but it does not solve the issue.

**Comment by jadjoubran** [comment]
Hi @kujtimiihoxha 
There are 2 issues here

1) Font awesome don't include their `css` in the `main` field in [bower.json](https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json)
This can be fixed maybe by using this [repository](https://github.com/components/font-awesome)? I never used it myself

2) You'd still have to copy the font files manually.. you can use the solution below
https://laracasts.com/discuss/channels/general-discussion/elixir-copypublish-fonts/replies/83236

Let me know if it works out for you :smile:

**Comment by kujtimiihoxha** [comment]
@jadjoubran  I will try this solution. About the fonts, I think it would be  great if the solution in  the discussion would be implemented in this starter. 

Thank you very much, and keep up the good work this starter is great.

**Comment by jadjoubran** [comment]
I understand your point view that you would expect this to work out of the box, hence it makes sense to add it..
However not all people would like to "publish" fonts and/or use font-awesome..
This is more elaborated in the docs: [overview](https://laravel-angular.readme.io/docs/overview#overview)

However, it would be great if you contribute back your solution in form of a recipe as explained here #149  and I'd be happy to add the guide to the documentation so that other users can benefit from it :smile:

**Comment by jadjoubran** [comment]
Hi @kujtimiihoxha 
Any updates on this?

**Comment by kujtimiihoxha** [comment]
@jadjoubran  I did not have any time to test this, as soon as I implement it on my project, I will write a recipe ;)

**Comment by jadjoubran** [comment]
Sounds great,thanks! 
Feel free to reopen if it doesn't work
