### ISSUE TITLE
Generators automatically register in corresponding files

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#239]
Creating a new component will automatically add a reference to this component in `index.components.js`
same for services & config
- [x] add auto-import config
- [x] components
- [x] services
- [x] config
- [x] filters
- [x] use auto-import for all generators
- [x] allow `--no-import` for all generators
- [x] update generators here
- [x] update config here

**Comment by flick36** [comment]
Hi, first time commenting, personally, i won't like this feature because i think the [John Papa’s Angular Style Guide](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md) it's easy and faster to mantain than the folder by feature architecture, in fact i would suggest a refactor on the starter using that styleguide, but of course it's just an opinion. any plans on realising the 3.2? i want to start a project but i'm not sure if i should wait or start using the unestable version

**Comment by jadsalhani** [comment]
Hi @flick36 

Thanks for the feedback! But I don't see how the starter is in violation of the John Papa style guide? If you take a look at this [rule](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y152), he personally recommends folder-by-feature + grouping everything inside a `main.module.js` file

Please note that the starter is using ES6 syntax and not regular Angular 1.5, so we are adapting as much as we can to the StyleGuide while maintaining the correct ES6 naming and syntax.

**Comment by jadjoubran** [comment]
Thanks @flick36 for your feedback
As @jadsalhani mentioned, we're doing our best to stick to John Papa's style guide
This feature would only replace the manual work of having to go into the `index.components.js` file to import the new component (same for filters, services, etc..)

I think 3.2 will be released in the coming 2 weeks
You can start using it though, it's stable most of the times (even though the tests are failing, that's just an issue with the test configuration)
