### ISSUE TITLE
Better solution for passing data to another state?

### ISSUE THREAD

**Issue by yosmelvin** [jadjoubran/laravel5-angular-material-starter#248]
Now I use localStorage, any other solution?

**Comment by jadsalhani** [comment]
Hi @yosmelvin 

Thanks for the question!
Since we're including [ui-router](https://github.com/angular-ui/ui-router) amongst the starter modules, you can use the `$stateParams` variable to send data between states.

For example, you can send the `name` variable while going to the `profile` state like so:

```
$state.go('profile', {name: this.name});
```

and in the `profile` component you can use it like so:

```
this.name = $stateParams.name
```

That way you can send and receive parameters between the different components your states navigate to

Hope this help!

**Comment by yosmelvin** [comment]
I am sorry, but its not working when I try your solution,
any other solution? because when passing like this 

```
this.state.go('dashboard.index', {name: 'testing'});
```

then

```
class MyController{
    constructor($log, $stateParams){
        'ngInject';

        this.log = $log;
        this.stateParams = $stateParams;
        this.log.debug(this.stateParams);
    }
}
```

it's will be display "object {}" on console

**Comment by jadsalhani** [comment]
My bad, I forgot to mention that when you want to add a state parameter to your states you need to declare it in the state definition.

So going back to my profile example, after the doing the above mentioned, one last step would be to declare/edit the profile state to have a variable in the url, like so

```
$state('profile, {
  url: '/profile/:name', //The name parameter you pass in the route
  data: {},
  views: {
  'main@': {
      templateUrl: getView('login')
   }
}
```

**Comment by jadjoubran** [comment]
Hi @yosmelvin 
Can you please confirm if this is working for you?

Thanks!

**Comment by yosmelvin** [comment]
It's work Thank you, but one more question how to send with post method ?

**Comment by jadjoubran** [comment]
Sounds great! 😄

Please open a new issue for the new question with a lot more details, it's unclear

Cheers
