### ISSUE TITLE
[Enhancement] Move the Dialog folder and less file

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#263]
I believe that the Dialog folder shouldn't been on the `angular` root folder, instead, as they're almost the same as components, they should be in `angular/app` or even in `angular/app/components` cause when you import a `Dialog Controller` into the controller you need it, you have to import it as: `import {DialogController} from '../../../dialogs/dialog/dialog.dialog.js';` and as you can see you have to go up folders to many times, and it looks "ugly", after all the dialogs are just templates with controllers, just as component are.

Also as they are, tempaltes they should have their .less file like the pages and the components

**Comment by jadjoubran** [comment]
Hi @flick36 
Indeed, it makes sense to have the dialogs inside the `angular/app` folder, mainly for consistency.

I think you could fix the paths issue by referencing an absolute path with `./dialogs` or `./angular/dialogs/`

However, we might hold off on fixing this for 3.2 because we want to minimize the breaking changes as much as possible and because we don't offer a lot of support with Angular Material dialogs for this release

Btw we're planning something great for Angular 2 😄
