### ISSUE TITLE
How to resolve a restangular in ui-router

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#270]
Hi, i want to use the resolve feature of the ui-router with restangular and i'm struggling to accomplish this in part, i believe for maybe the same reasons Dialogs are a pain in the assfor the import thing, but i tried to do the same thing i did in #245 but without success, so maybe an example of how i can accomplish this? because the ui-router sends you to the page where i have the components (just 1 in this case) but the component has it's own controller and i need to use the resolves in that controller on that component

**Comment by jadjoubran** [comment]
I've never used resolves in ui-router because they don't deliver a good UX.

Having said that, if you still want to proceed, ui-router's `resolve` expects a json object with keys and functions. So you must provide a function.. Placing those functions inside ui-router wouldn't be very nice.. this means you'd have to create your own "place" for that and you'd need to import those functions accordingly

Take a look at this [tutorial](https://medium.com/opinionated-angularjs/advanced-routing-and-resolves-a2fcbf874a1c#.rk5zdued9).

**Comment by flick36** [comment]
Thanks! i appreciatte the suggest, and the tutorial!
