### ISSUE TITLE
Without localhost port the build/css and build/js path point to directly localhost

### ISSUE THREAD

**Issue by aarukarthiga** [jadjoubran/laravel5-angular-material-starter#300]
I have tried to launch the application like "h**ttp://localhost/laravel5-angular-material-starter/public/**"

But i'm getting the error in console **"NetworkError: 404 Not Found - http://localhost/build/css/vendor-0c77a86012.css"**

If i use php artisan serve --port=8080 ..It's working fine.

How to host the files into my server with this issue?

Anyone please help?

And also i can't able to use kendo in the angular component

**Comment by jadjoubran** [comment]
Hi @aarukarthiga 
I think your issue here is that you ran `php artisan serve` from inside the `public` folder.. It should be ran at the root directory

Let me know if it fixes it for you

**Comment by flick36** [comment]
> I think your issue here is that you ran php artisan serve from inside the public folder.. It should be ran at the root directory

@jadjoubran but the OP doesn't want to use php artisan serve, to serve the app.

@aarukarthiga if your app it's finished, then you can edit the `index.blade.php` file on line `7` and `8` 

```
<link rel="stylesheet" href="{!! elixir('css/vendor.css') !!}">
<link rel="stylesheet" href="{!! elixir('css/app.css') !!}">
```

and manually set the css and js file that were generated when you last use the `gulp` command, or even changue the name of those files to have something like: 

```
<link rel="stylesheet" href="css/vendor.css">
<link rel="stylesheet" href="css/app.css">
```
that happens because the starter uses the [elixir version task](https://laravel.com/docs/5.2/elixir#versioning-and-cache-busting) to 

>  force browsers to load the fresh assets instead of serving stale copies of the code.

**Comment by aarukarthiga** [comment]
I have moved my index.php and .htaccess file to my root directory. Because i don't want to public in my url .. and i don't like to use artisan serve with port.

I would like to always run my laravel application in root directory name itself. If i give absolute path to like  <link rel="stylesheet" href="{{URL::to('public/')}}{!! elixir('css/vendor.css') !!}"> 

Then it's working fine .

Thanks
