### ISSUE TITLE
Setting Auth to true causes infinite loop when unauthenticated

### ISSUE THREAD

**Issue by ixperiencenl** [jadjoubran/laravel5-angular-material-starter#315]
When I set the auth: true in routes.config.js the app crashes and gives me a RangeError: Maximum call stack size exceeded - this is caused by an infinite loop I guess.

The crash occurs in routes.run.js on line 11:
 return $state.go('app.login');

It looks like the login controller has to be outside the auth but please put this into the documentation so newbies (like me with Restangular) know where to look for it.

**Comment by flick36** [comment]
I don't quite understand your problem

1.- Are you using it inside the data attribute? as: `data: {auth: true},`
2.- Where are you using `auth: true` because it sounds like you are triying to use it on the login page so,

Think a little bit ok? if you required the user to be logged in in the login page... how are they supose to log in? i mean? that's redundant. it's not about you being newbie to Restangular, it's about a little bit of logic, that's why i don't think it should be in the docs?

**Comment by jadjoubran** [comment]
Hi @ixperiencenl 
Any updates on this?

**Comment by solovieff** [comment]
Seems that I'm having the same issue or something similar:
<img width="529" alt="screen shot 2016-06-03 at 14 33 12" src="https://cloud.githubusercontent.com/assets/5033247/15789095/842cb64e-2998-11e6-8cc3-cd4c59fa0a12.png">
<img width="699" alt="screen shot 2016-06-03 at 14 34 32" src="https://cloud.githubusercontent.com/assets/5033247/15789099/889cb724-2998-11e6-96e9-b34ff4a96952.png">

Didn't edit anything at this point from the default installation.

**Comment by flick36** [comment]
You should not use `data: {auth: true}` in the abstract route, that's like a said before redundant, you should use it individually on every state you have. for example: 

```
.state('app.services', {
        url: '/services',
        data: { auth: true },
        views: {
            'content@app': {
                templateUrl: getView('services')
            }
        }
    })
```

every state that requires to be logged in in order to acces there's where you want to put the `data: {auth: true}`

**Comment by solovieff** [comment]
Many thanks! I think you should close this issue.

**Comment by flick36** [comment]
Only the OP, @jadjoubran or other moderator can close it, but yes i think this is solved @jadjoubran
