### ISSUE TITLE
How to add Angular Material template

### ISSUE THREAD

**Issue by mudin3i** [jadjoubran/laravel5-angular-material-starter#319]
Hello,

It is my first time to use Laravel and AngularJS integration.
This starter is pretty awesome.
Now I bought Fuse Angular Material template and wanna install it.
Could you give any suggestion for this?

I am worried to rebuild my whole structure again after some time.
So before starting, I need support from experienced people.
I wanna make really perfect and secured project using laravel 5.2, angular 1.5.5 with Fuse template, RESTful API, JWT Authentication,...

Thank you very much

Mudin

**Comment by odyright** [comment]
Hello @Mudin i already did it. First of all yes @jadjoubran did a good work, you could use the starter project of @jadjoubran but a fresh installation of laravel is better. Refer to this: [fuse & laravel](https://github.com/withinpixels/fuse/issues/112) & [my old request](https://laracasts.com/discuss/channels/elixir/i-require-elixir-and-bower-configuration-help)
1. If you decided to use this starter project approach you'll need to edit the Elixir's gulp process & the files inside the tasks folder of this starter project, because the fuse theme has his own `gulpfile.js` so you'll work with the folders & files inside the `src` folder of fuse... (if you need more explication..let me know) 
2. If you use a fresh install of laravel refer to the link i gave above.

**Comment by mudin3i** [comment]
Hi Daniel,
I will check it.
Thanks a lot

**Comment by odyright** [comment]
also if you find a better way let me know.

**Comment by mudin3i** [comment]
Daniel,

I didn't get anything in "your old request".
What Ruffles suggested is putting fuse files inside resources/assets/{css or js}.
This is how I am doing now in my project without this starter and without Fuse template.

My gulpfile.js is currently like this: 

`elixir(function(mix) {
    mix.sass('app.scss');

```
mix.scripts([
    'app.editor.js',
    'controllers/core.editor.js',
    'controllers/main.editor.js',
    'controllers/vrTour.editor.js',
    'controllers/scene.editor.js',
    'controllers/asset.editor.js',
    'controllers/hotspot.editor.js',
    'controllers/marker.editor.js',
    'services/sceneService.js',
    'directives/myBlur.js',
    'directives/myFocus.js',
], 'public/js/editor.js');
```

});`

And I think it is not well structured. It would be nice if it is like Fuse or this starter.
Can u share ur gulpfile and file structure?

Thanks

**Comment by flick36** [comment]
why is this here? this is not a starter issue :S Fuse has his own [repository ](https://github.com/withinpixels/fuse/) you should ask this there

**Comment by mudin3i** [comment]
Yeah you are right. Sorry.

But I believe that here are more people who are good at laravel and angular integration.
It is not an issue. I just need suggestion

**Comment by flick36** [comment]
You also have [Stack Overflow](http://stackoverflow.com/)

**Comment by flick36** [comment]
Changing the title, won't changue the fact that this shouldn't be here, but okey...

1.- You can use this starter to handle the backend because well this already has JWT although it's really not that hard to implement it on a fresh laravel installation and that's all you need from this starter apparently.

2.- I own Fuse template as well... so i can tell you you don't have to mix them (the starter and the template) that will just complicate things you know? because each one (the starter and the template) has they're own gulpfiles and bower's dependencies, so just use the template as your front end, all you have to set it's the route to your RESTFUL API.

if you want to complicate.. well you'll have to hack into the code of both the template and the starter to mix the gulp tasks en the bower dependancies, wich in the future when the starter or the template updates, you might have to do all that procces of adjusting the tasks and dependencies.

**Comment by mudin3i** [comment]
@flick36, 
This is gonna be great help for me. 
Thank you very much :)
