### ISSUE TITLE
Angular component TDD

### ISSUE THREAD

**Issue by pooniv** [jadjoubran/laravel5-angular-material-starter#320]
How could i test the angular component ?? 

For testing laravel api's , phpunit command used for unit test...

What about angular? any commands ?

**Comment by flick36** [comment]
The starter uses [ng-describe](https://github.com/kensho/ng-describe), and everytime you generate a `component, direcive, service or config` with the [laravel-ng-artisan-generators](https://github.com/jadjoubran/laravel-ng-artisan-generators) a test it's created in the `tests/angular` folder, and here's a [ng-describe tutorial](https://glebbahmutov.com/blog/1-2-3-tested/) (the same one the author's library recommends)

**Comment by pooniv** [comment]
@flick36 .. Thank you...

Can you explain how the elixir, bower , bower tasks working in laravel material 

In elixir Json

```

{
    "js": {
        "outputFolder": "public/js"
    },
    "css": {
        "outputFolder": "public/css",
        "less": {
            "folder": "../../angular/"
        }
    }
}
```

the output folder indicating compiled css and scripts stored path or reading from css , scripts from the folder?

I have my index.php , and .htaccess in root ..

If i run the gulp it's always looking 

```
     resources\assets\js\public\js\vendor.js <-- Not Found
   - resources\assets\js\public\js\partials.js <-- Not Found
   - resources\assets\js\public\js\app.js <-- Not Found
```

I'm new to elixir and bower

**Comment by flick36** [comment]
Basically [elixir](https://laravel.com/docs/5.2/elixir) is just a laravel extension to easily use gulp on laravel, 

> Laravel Elixir provides a clean, fluent API for defining basic Gulp tasks for your Laravel application. 

So if you open your `gulpfile.js`on line `36` you'll se it's calling the tasks that are stored in the `tasks` folder on the root project folder and they can almost be read as `pseudo-code`.

Those paths, indicates where to save/read the compiled files from the tasks as you can see in for example lines `20 & 21` of `tasks/bower.task.js` file althoug the final compiled versions are stored in `public/build/ css & js` folder because the starter uses [Versioning / Cache Busting](https://laravel.com/docs/5.2/elixir#versioning-and-cache-busting) wich 

>  suffix compiled assets with a timestamp or unique token to force browsers to load the fresh assets instead of serving stale copies of the code.

at least you have change something it shouldn't be looking in `resources\assets\*` but in `public\*`

**Comment by pooniv** [comment]
@flick36 ..

I want to use bootstrap and font awesome, so i have just used `bower install bootstrap-sass-official`

package installed under bower_components, how do i use the bootstrap css and js as well font awesome to compile using elixir

Do i need to add the bootstrap style path to elixir.json file `mix.scss('bower_component/bootstrap/asset/')`???

I'm not understanding the bower.task.js file ...were they mentioned read file for compile ? always my script reading resource/assets only in that file they have a line

`@import "bower_components/bootstrap-sass-official/assets/";`

**Comment by flick36** [comment]
use `bower install bootstrap-sass-official --save` and that's all, it'll be imported automatically to your `bower.json` and it'll be automatically compile thanks to the `bower task`

for fontawesome the same: `bower install font-awesome --save` with this you may have some problems, what i did was copy the `fonts` folder inside `bower_components/font-awesome` (once you download it of course) to `public/build` and in my `bower.json` file i added at the very end:

```
"overrides": {
    "font-awesome": {
      "main": [
        "./css/font-awesome.css",
        "./fonts/*"
      ]
    }
}
```

I don't really use the fontawesome fonts, but a library i use does, that's why i did that ugly fix... any way i'm planning on delet them from my project so you should really find a better way, or if you want to keep it with this well.. it works xD
