### ISSUE TITLE
How to setup multi-tenancy in routes.run.js

### ISSUE THREAD

**Issue by maimash** [jadjoubran/laravel5-angular-material-starter#329]
- **I'm submitting a  support request

I have setup a mentor and mentee middleware in laravel and setup the routes accordingly and they are working fine. However, I am not able to replicate the same behaviour on Angular front end routes as there is no way to identify the user type from Satellizer.

The only function in isAuthenticated() which only checks whether the user is auth or not. How can I define custom locks for different user types.

Can anyone help?

**Comment by flick36** [comment]
https://laravel-angular.readme.io/docs/authenticated-routes-front-end

If you open the `angular/config/routes.config.js` file, you notice that we're passing an empty `data: {}` parameter which every state inherits because it's set on the abstract route `app`.

Although this is an optional argument, we've implemented a custom logic in `angular/run/routes.run.js` that reads this value from inside this `data` object and sets authentication accordingly.

if you set

```
data: {
     auth: true
}
```

then those routes become protected. They would require authentication.

This behaviour can be enabled on a per route basis. Or per a group of routes, by creating abstract routes.

You can also extend this behaviour by setting a string value to auth, such as: `auth: 'admin`'. And then you would implement your own logic in `routes.run.js`.

**Comment by maimash** [comment]
I totally get it.. But how can I identify which user is Admin or which is a
normal user? I have even setup a user type field to segregate user and
Admin in the dB. But how to configure it routes.run

**Comment by flick36** [comment]
It's up to you to implement the logic you want, and there are millions of ways to do that here's one example, the most easier one, i believe, it's to create a service, for example: `AccountService` where you have a `setter` and a `getter` function tiny example:

```
export class AccountService {
    constructor($localStorage, $state, $auth) {
        'ngInject';

        this.$localStorage = $localStorage;
        this.$auth = $auth;
        this.$state = $state;
    }

    setUser(user) {
        this.$localStorage.user = user;
    }

    getUser() {
        return this.$localStorage.user;
    }

    logout() {
        this.$auth.logout().then(() => {
            this.$localStorage.$reset();
            this.$state.go('app.login');
        });
    }
}
```

Ok he have our `AccountService` now what this does, it's save the user information you have on your db into a cookie, now how can i save that user information in there? easy, just inject our newly created `AccountService` into the `login` controller

and when the user succesfully log in right when you set the token in line:

```
this.$auth.login(user)
            .then((response) => {
                this.$auth.setToken(response.data);
...
```

you wanna call the `setUser` we just create in our `AccountService` like this: `this.AccountService.setUser(response.data.data.user);`

Cool now you have set all the user info into a cookie and you have a service to easily access that information how would you do that you ask? 

Easy, so let's inject our `AccountService` into our `routes.run.js`, and we implement our own logic as the documentation said. For example if my user it's an `admin` i can do this:

```
export function RoutesRun($state, $transitions, AccountService) {
    'ngInject';

    let user = AccountService.getUser();

    let requiresAuthCriteria = {
        to: ($state) => $state.data && ($state.data.auth === user.type)
    };

    let redirectToLogin = ($auth) => {
        'ngInject';
        if (!$auth.isAuthenticated()) {
            return $state.target('app.login', undefined, {location: false});
        }
    };

    $transitions.onBefore(requiresAuthCriteria, redirectToLogin, {priority:10});
}
```

This would check if the `data: {'admin'}` you have in your route matches with the user type information you have in your cookie, if it doesnt match it would return the user to the login page (you can chage this behavior to on the `redirectToLogin` by adding a new if with the same comparision we made on the `requiresAuthCriteria` to instead of redirect to the login page show a message instead for example) 

The important thing here it's the user variable that gets the user that its logged in and saved in our cookie, this in most cases should be a JSON object that may have all the fields of the DB regarding that user for example if my DB has

name | type 

my JSON object looks like:

```
{
    name: 'Flick'
    type: 'admin'
}
```

^ this is just a JSON example

**Comment by maimash** [comment]
To update the login function do i need to edit the satellizer.js or can i define an override login function in satellizer.config?

**Comment by flick36** [comment]
No, you don't touch the `satellizer.config` for pretty much nothing

**Comment by maimash** [comment]
Then how can i alter the login function as I cannot see it any of the editable files

**Comment by flick36** [comment]
`RootFolder/angular/app/components/login-form/login-form.component.js`

**Comment by maimash** [comment]
Thank you very much.. i completely missed that :)

**Comment by maimash** [comment]
It does not seem to work. I have defined auth route such as admin and customer however it does not work and if there is no user is logged in. I keep getting user is undefined.

**Comment by flick36** [comment]
Mine was just an example, a very basic one, as I said you have to implement your own logic to the app, it's expected to get `user is undefined` if no one is logged in, at least with my example because you only fill the user variable once someone logs in... I think your problem it's more about a logic on your app than a real starter issue, i can help you, yes, but not in here since as i say it's not a real starter issue, you can email me if you want, or we can talk in the [gitter of this repository](https://gitter.im/jadjoubran/laravel5-angular-material-starter), you even have [StackOverflow](https://stackoverflow.com/) or [Codementor](https://www.codementor.io) in this one you can even find [@jadjoubran](https://www.codementor.io/jadjoubran) I'm willing to help you but i think if i help you here, we will be extending the conversation because i'll have to see some code, and how's your database formed and all that.

**Comment by maimash** [comment]
Okay. I understand. I will configure my full set of logic to make this work
first. If I am unsuccessful will follow it up on stack or code mentor. Will
share final codes once I am successful.

**Comment by flick36** [comment]
Sure, as i said feel free to email me if you want, or you can create a repository and share it so i can see your code and make it work :smile:
