### ISSUE TITLE
Help Directives

### ISSUE THREAD

**Issue by proxnoob06** [jadjoubran/laravel5-angular-material-starter#344]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

Hello,

Can you help me to convert this directive from ecma6?

Source: Angular-File-Upload..

[https://github.com/nervgh/angular-file-upload/blob/v2.2.0/examples/image-preview/directives.js#L21](url)

`'use strict';

angular

```
.module('app')


// Angular File Upload module does not include this directive
// Only for example


/**
* The ng-thumb directive
* @author: nerv
* @version: 0.1.2, 2014-01-09
*/
.directive('ngThumb', ['$window', function($window) {
    var helper = {
        support: !!($window.FileReader && $window.CanvasRenderingContext2D),
        isFile: function(item) {
            return angular.isObject(item) && item instanceof $window.File;
        },
        isImage: function(file) {
            var type =  '|' + file.type.slice(file.type.lastIndexOf('/') + 1) + '|';
            return '|jpg|png|jpeg|bmp|gif|'.indexOf(type) !== -1;
        }
    };

    return {
        restrict: 'A',
        template: '<canvas/>',
        link: function(scope, element, attributes) {
            if (!helper.support) return;

            var params = scope.$eval(attributes.ngThumb);

            if (!helper.isFile(params.file)) return;
            if (!helper.isImage(params.file)) return;

            var canvas = element.find('canvas');
            var reader = new FileReader();

            reader.onload = onLoadFile;
            reader.readAsDataURL(params.file);

            function onLoadFile(event) {
                var img = new Image();
                img.onload = onLoadImage;
                img.src = event.target.result;
            }

            function onLoadImage() {
                var width = params.width || this.width / this.height * params.height;
                var height = params.height || this.height / this.width * params.width;
                canvas.attr({ width: width, height: height });
                canvas[0].getContext('2d').drawImage(this, 0, 0, width, height);
            }
        }
    };
}]);`
```

Sorry guys new from here.

Thanks and Advance!

**Comment by jadjoubran** [comment]
Hi @proxnoob06 
do you mean convert it **to** ES6?

**Comment by proxnoob06** [comment]
yes @jadjoubran.. but it working now.. my new problem is how to use => in callback function please see code below,

```
constructor($log , FileUploader){
        'ngInject';

        this.$log = $log;
        this.uploader = new FileUploader({
            url:'api/upload',
            //autoUpload:true,
            name:'kim',
            isUploading:true,
            formData:[{filename:'testfilename'}],
            removeAfterUpload:true

        });
        this.uploader.onAfterAddingFile = this.onAfterAddingFile;     
}
//working
onAfterAddingFile(item){
        console.log(item); // working
        this.$log.info(item) // error:Uncaught TypeError: Cannot read property 'info' of undefined

}
//error
onAfterAddingFile(item)=>{
        this.$log.info('test');
})
```

**Comment by flick36** [comment]
This should work:

```
constructor($log , FileUploader){
'ngInject';

    this.$log = $log;
    this.uploader = new FileUploader({
        url:'api/upload',
        //autoUpload:true,
        name:'kim',
        isUploading:true,
        formData:[{filename:'testfilename'}],
        removeAfterUpload:true

    });
    this.uploader.onAfterAddingFile = this.onAfterAddingFile;    
    this.onAfterAddingFile = (item) => {
        console.log(item);
        this.$log.info(item);
    }
}
```

**Comment by proxnoob06** [comment]
Thank you verry much @flick36 !

**Comment by proxnoob06** [comment]
H i@flick36n

How can i inject/use  directives like example above?? there's a way to use that without converting to ecma script? what i did is inject into existing bower modules because i saw they are same code pattern but that is wrong.

Thanks in Advance!

**Comment by flick36** [comment]
Don't think about ECMAScript as a different language, ECMAScript it's just a standard and JavaScript it's like the implementation of those standards... it's almost like AngularJS, React, EmberJS, they're all based on JavaScript right? they're just have their own conventions, well JavaScript follows ECMAScript conventions... This is a nice image @jadjoubran post https://github.com/jadjoubran/laravel5-angular-material-starter/issues/339#issuecomment-227069866 ES5 is just the JavaScript you are more familiar with and the one for now almost every directives, scripts etc.. are based on, but as the image shows they're completly compatible in newer versions of EcmaScript, therefore you'll just inject/user directives, the same way you have being doin it.

I'll take [Angular File Upload](https://github.com/nervgh/angular-file-upload) as an example

1.- Add the directive you want in your bower dependency manually or with the code their githubpage gives you: `bower install angular-file-upload --save` i've just add the `--save` flag so it would save into my current `bower.json` automatically

2.- Then in my `/RootFolder/angular/index.modules.js` file i'll add the module dependency in this case: `'angularFileUpload'`. Now you'll see when you open the file you have a bunch of lines already there, but we only focuse on the `angular.module('app.components', [` one, in there on every other component you'll have you just add a "," at the end and you'll add your directive in this case i'll end out with something like this:

```
angular.module('app.components', [
    'ui.router',
    'ngMaterial',
    'angular-loading-bar',
    'restangular',
    'ngStorage',
    'satellizer',
        'ngMessages',

        'angularFileUpload'
]);
```

3.- Then i'll just run gulp
4.- Then i'll just inject it in any controller i want to use that directive in it's controller as my example above...

Now sometimes you can came across the problem you had when you first open this issue, you made everything correct but when you tried to use it in a function well it broke and that's because of the [**Lexical this**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this) but you can fix this (as i do in my  previous example) with [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) ;) 

if you look closely it's all i did to your code for it to work :D i've just convert your function, note that arrow functions should be declared inside the contructor preferently

**Comment by proxnoob06** [comment]
Thank you verry much @flick36 .
in comment above the author Angular File Upload said  "does not include this directive" (ngThumb)
i was confused how to add that directive in my directives files if the directive  given codes are different from standard coding. 

Thanks...
