### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by Fiodor94** [jadjoubran/laravel5-angular-material-starter#450]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**

Since I upgraded to version 3.4.0, I keep seeing this "warning" in the javascript console and it doesn't load my page at all.

Error:
Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

Is there a way to take it off ? 

Thanks !

* **Laravel & Angular version:** 3.4.0

**Comment by flick36** [comment]
You have to use `https` since 3.4.0 is pro [Progressive Web App](https://developers.google.com/web/progressive-web-apps/) you have to create ssl certificates, provide info on what SO you use, and what do you use to mount your server? if you need help on how to create the certificates

**Comment by Fiodor94** [comment]
I'm using Laragon. Is there a way to "disable" the Progressive Web App ?

Thanks.

**Comment by flick36** [comment]
Laragon plays well with progressive apps, since it autocreates SSL virtual hosts (i use it myself). Sure there are 2 ways, 1st implies you modifiying the code to remove progressive app code, 2: or use version 3.2.x as mentioned [in the docs](https://laravel-angular.readme.io/docs#which-version-should-you-use-34-or-32)

**Comment by Fiodor94** [comment]
Thanks !
