### ISSUE TITLE
Angular UI Bootstrap

### ISSUE THREAD

**Issue by Fiodor94** [jadjoubran/laravel5-angular-material-starter#459]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**

Has anybody have issues adding the Angular UI bootstrap to the project ? I tried it installing it via Bower and NPM without any results. Every time I try to test a code snippet nothing happens. I get no errors in the console log either.

Any ideas what could it be ?

Thanks !

* **Got code samples?**
Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
Also make sure to click on the *Preview* button to double check your code formatting

* **Laravel & Angular version:** 3.4.0

**Comment by flick36** [comment]
Wow! Ok se heres the deal, this starter uses angular material, why would you wanna use ui bootstrap? If you wanna use angular ui, ill totally recomend you to use another starter, because this one will be useless. Right now im not in my computer but ill edit this comment to rocommend you some other one or guide you on how to use angular ui

EDIT: @Fiodor94 Ok so this one is pretty much the same but without the angular boilerplate: https://github.com/francescomalatesta/laravel-api-boilerplate-jwt you should check it out.

But if you want something really close to this starter, chek the one made by @silverbux https://github.com/silverbux/laravel-angular-admin its exactly the same as this but uses Angular-UI instead of angular material and have some nice additions as you can read in the repo ;)

There are a lot others, check them out here: https://github.com/chiraggude/awesome-laravel#starter-projects

**Comment by Fiodor94** [comment]
The reason i want to use Angular UI is because I can't make Angular-Paging or pagination working. Every time I try to add it via bower I get this error:

uncaught referenceerror require is not defined and the error goes directly to 👍 
var grunt = require('grunt')

Thanks a lot !
