### ISSUE TITLE
Deprecate bower

### ISSUE THREAD

**Issue by infacq** [jadjoubran/laravel5-angular-material-starter#5]
I think laravel has provide enough tools beside `npm` also is basic requirement for elixir. Why not just use npm for dependency management

**Comment by jadjoubran** [comment]
I'm already using `npm` for node.js dependency management. However I'm using `bower` for front-end dependency management because bower offers a flat dependency tree which is much more convenient for front end.
For more information on the difference between `npm` and `bower` http://stackoverflow.com/a/18652918/1599122

Are you suggesting to use npm with browserify?

**Comment by infacq** [comment]
i thought this has solve the problem 

https://www.npmjs.com/package/angular-material

to manage the depedencies. Correct me if I'm wrong

**Comment by jadjoubran** [comment]
If you want to use npm to resolve your dependencies you need to use a tool such as `browserify`. So it's not only about this package (npmjs.com/package/angular-material) you have to install all the front-end dependencies using npm and then loading them with `browserify`.
But then again the difference between `npm` and `bower` would mainly be the dependency resolution (bower has aflat dependency tree which is much more convenient for front-end development)

**Comment by infacq** [comment]
thanks for your reply. This conversation has drive me to get deeper into Browserify. I feel singlelify all the js file under browserify is really awesome. Laravel has update their elixir library which can manage all the npm dependencies. You should check it out. Thanks brother

**Comment by jadjoubran** [comment]
Will do, thanks a lot!
